"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ActivityOptionEnum = exports.RefundFeeTypeEnum = exports.FilePurposeEnum = exports.ReturnStateEnum = exports.ReturnCountFilterEnum = exports.DecisionEnum = exports.EscalateReasonEnum = exports.GetReturnFieldGroupEnum = exports.ReturnTypeEnum = exports.RequestTypeEnum = exports.ReturnReasonEnum = exports.ShippingCarrierEnum = exports.InquiryStatusFilter = exports.CaseSearchFieldGroup = exports.CaseStatusFilter = exports.InquirySearchFieldGroup = exports.UserRoleFilter = void 0;
var UserRoleFilter;
(function (UserRoleFilter) {
    UserRoleFilter["BUYER"] = "BUYER";
    UserRoleFilter["SELLER"] = "SELLER";
})(UserRoleFilter = exports.UserRoleFilter || (exports.UserRoleFilter = {}));
var InquirySearchFieldGroup;
(function (InquirySearchFieldGroup) {
    InquirySearchFieldGroup["DEFAULT"] = "DEFAULT";
    InquirySearchFieldGroup["SUMMARY"] = "SUMMARY";
})(InquirySearchFieldGroup = exports.InquirySearchFieldGroup || (exports.InquirySearchFieldGroup = {}));
var CaseStatusFilter;
(function (CaseStatusFilter) {
    CaseStatusFilter["CLOSED"] = "CLOSED";
    CaseStatusFilter["CS_CLOSED"] = "CS_CLOSED";
    CaseStatusFilter["ON_HOLD"] = "ON_HOLD";
    CaseStatusFilter["OPEN"] = "OPEN";
    CaseStatusFilter["OTHER"] = "OTHER";
    CaseStatusFilter["REFUND_AGREED_BUT_FAILED"] = "REFUND_AGREED_BUT_FAILED";
    CaseStatusFilter["WAITING_CS"] = "WAITING_CS";
    CaseStatusFilter["WAITING_DELIVERY"] = "WAITING_DELIVERY";
})(CaseStatusFilter = exports.CaseStatusFilter || (exports.CaseStatusFilter = {}));
var CaseSearchFieldGroup;
(function (CaseSearchFieldGroup) {
    CaseSearchFieldGroup["DEFAULT"] = "DEFAULT";
    CaseSearchFieldGroup["SUMMARY"] = "SUMMARY";
})(CaseSearchFieldGroup = exports.CaseSearchFieldGroup || (exports.CaseSearchFieldGroup = {}));
var InquiryStatusFilter;
(function (InquiryStatusFilter) {
    InquiryStatusFilter["CLOSED"] = "CLOSED";
    InquiryStatusFilter["CLOSED_WITH_ESCALATION"] = "CLOSED_WITH_ESCALATION";
    InquiryStatusFilter["CS_CLOSED"] = "CS_CLOSED";
    InquiryStatusFilter["OPEN"] = "OPEN";
    InquiryStatusFilter["OTHER"] = "OTHER";
    InquiryStatusFilter["PENDING"] = "PENDING";
    InquiryStatusFilter["WAITING_BUYER_RESPONSE"] = "WAITING_BUYER_RESPONSE";
    InquiryStatusFilter["WAITING_SELLER_RESPONSE"] = "WAITING_SELLER_RESPONSE";
})(InquiryStatusFilter = exports.InquiryStatusFilter || (exports.InquiryStatusFilter = {}));
var ShippingCarrierEnum;
(function (ShippingCarrierEnum) {
    ShippingCarrierEnum["AUSTRALIA_POST"] = "AUSTRALIA_POST";
    ShippingCarrierEnum["BARTOLINI"] = "BARTOLINI";
    ShippingCarrierEnum["CANADA_POST"] = "CANADA_POST";
    ShippingCarrierEnum["COLISSIMO"] = "COLISSIMO";
    ShippingCarrierEnum["COLLECT_PLUS"] = "COLLECT_PLUS";
    ShippingCarrierEnum["CORREOS"] = "CORREOS";
    ShippingCarrierEnum["DEUTSCHE_POST"] = "DEUTSCHE_POST";
    ShippingCarrierEnum["DHL"] = "DHL";
    ShippingCarrierEnum["FEDEX"] = "FEDEX";
    ShippingCarrierEnum["HERMES"] = "HERMES";
    ShippingCarrierEnum["LA_POSTE"] = "LA_POSTE";
    ShippingCarrierEnum["MONDIAL_RELAY"] = "MONDIAL_RELAY";
    ShippingCarrierEnum["MRW"] = "MRW";
    ShippingCarrierEnum["NEXIVE"] = "NEXIVE";
    ShippingCarrierEnum["OTHER"] = "OTHER";
    ShippingCarrierEnum["PARCEL_FORCE"] = "PARCEL_FORCE";
    ShippingCarrierEnum["POSTE"] = "POSTE";
    ShippingCarrierEnum["ROYAL_MAIL"] = "ROYAL_MAIL";
    ShippingCarrierEnum["SEUR"] = "SEUR";
    ShippingCarrierEnum["UNKNOWN"] = "UNKNOWN";
    ShippingCarrierEnum["UPS"] = "UPS";
    ShippingCarrierEnum["USPS"] = "USPS";
})(ShippingCarrierEnum = exports.ShippingCarrierEnum || (exports.ShippingCarrierEnum = {}));
var ReturnReasonEnum;
(function (ReturnReasonEnum) {
    ReturnReasonEnum["ARRIVED_DAMAGED"] = "ARRIVED_DAMAGED";
    ReturnReasonEnum["ARRIVED_LATE"] = "ARRIVED_LATE";
    ReturnReasonEnum["BUYER_CANCEL_ORDER"] = "BUYER_CANCEL_ORDER";
    ReturnReasonEnum["BUYER_NO_SHOW"] = "BUYER_NO_SHOW";
    ReturnReasonEnum["BUYER_NOT_SCHEDULED"] = "BUYER_NOT_SCHEDULED";
    ReturnReasonEnum["BUYER_REFUSED_TO_PICKUP"] = "BUYER_REFUSED_TO_PICKUP";
    ReturnReasonEnum["DEFECTIVE_ITEM"] = "DEFECTIVE_ITEM";
    ReturnReasonEnum["DIFFERENT_FROM_LISTING"] = "DIFFERENT_FROM_LISTING";
    ReturnReasonEnum["EXPIRED_ITEM"] = "EXPIRED_ITEM";
    ReturnReasonEnum["FAKE_OR_COUNTERFEIT"] = "FAKE_OR_COUNTERFEIT";
    ReturnReasonEnum["FOUND_BETTER_PRICE"] = "FOUND_BETTER_PRICE";
    ReturnReasonEnum["IN_STORE_RETURN"] = "IN_STORE_RETURN";
    ReturnReasonEnum["MISSING_PARTS"] = "MISSING_PARTS";
    ReturnReasonEnum["NO_LONGER_NEED_ITEM"] = "NO_LONGER_NEED_ITEM";
    ReturnReasonEnum["NO_REASON"] = "NO_REASON";
    ReturnReasonEnum["NOT_AS_DESCRIBED"] = "NOT_AS_DESCRIBED";
    ReturnReasonEnum["ORDERED_ACCIDENTALLY"] = "ORDERED_ACCIDENTALLY";
    ReturnReasonEnum["ORDERED_DIFFERENT_ITEM"] = "ORDERED_DIFFERENT_ITEM";
    ReturnReasonEnum["ORDERED_WRONG_ITEM"] = "ORDERED_WRONG_ITEM";
    ReturnReasonEnum["OTHER"] = "OTHER";
    ReturnReasonEnum["OUT_OF_STOCK"] = "OUT_OF_STOCK";
    ReturnReasonEnum["RETURNING_GIFT"] = "RETURNING_GIFT";
    ReturnReasonEnum["VALET_DELIVERY_ISSUES"] = "VALET_DELIVERY_ISSUES";
    ReturnReasonEnum["VALET_UNAVAILABLE"] = "VALET_UNAVAILABLE";
    ReturnReasonEnum["WRONG_SIZE"] = "WRONG_SIZE";
})(ReturnReasonEnum = exports.ReturnReasonEnum || (exports.ReturnReasonEnum = {}));
var RequestTypeEnum;
(function (RequestTypeEnum) {
    RequestTypeEnum["CREATE"] = "CREATE";
    RequestTypeEnum["REQUEST"] = "REQUEST";
    RequestTypeEnum["UNKNOWN"] = "UNKNOWN";
})(RequestTypeEnum = exports.RequestTypeEnum || (exports.RequestTypeEnum = {}));
var ReturnTypeEnum;
(function (ReturnTypeEnum) {
    ReturnTypeEnum["EXCHANGE"] = "EXCHANGE";
    ReturnTypeEnum["MONEY_BACK"] = "MONEY_BACK";
    ReturnTypeEnum["REPLACEMENT"] = "REPLACEMENT";
    ReturnTypeEnum["UNKNOWN"] = "UNKNOWN";
})(ReturnTypeEnum = exports.ReturnTypeEnum || (exports.ReturnTypeEnum = {}));
var GetReturnFieldGroupEnum;
(function (GetReturnFieldGroupEnum) {
    GetReturnFieldGroupEnum["FULL"] = "FULL";
    GetReturnFieldGroupEnum["NONE"] = "NONE";
    GetReturnFieldGroupEnum["SUMMARY"] = "SUMMARY";
})(GetReturnFieldGroupEnum = exports.GetReturnFieldGroupEnum || (exports.GetReturnFieldGroupEnum = {}));
var EscalateReasonEnum;
(function (EscalateReasonEnum) {
    EscalateReasonEnum["BUYER_NORESPONSE"] = "BUYER_NORESPONSE";
    EscalateReasonEnum["BUYER_RETURNED_WRONG_ITEM"] = "BUYER_RETURNED_WRONG_ITEM";
    EscalateReasonEnum["DISAGREE_WITH_RETURN_REASON"] = "DISAGREE_WITH_RETURN_REASON";
    EscalateReasonEnum["ITEM_NOT_RECEIVED"] = "ITEM_NOT_RECEIVED";
    EscalateReasonEnum["ITEM_RECEIVED_IN_DIFFERENT_CONDITION"] = "ITEM_RECEIVED_IN_DIFFERENT_CONDITION";
    EscalateReasonEnum["NEW_ITEM_NOT_RECEIVED"] = "NEW_ITEM_NOT_RECEIVED";
    EscalateReasonEnum["NO_REFUND_FOR_RETURN_SHIPPING"] = "NO_REFUND_FOR_RETURN_SHIPPING";
    EscalateReasonEnum["NO_REFUND_RECEIVED"] = "NO_REFUND_RECEIVED";
    EscalateReasonEnum["OTHER"] = "OTHER";
    EscalateReasonEnum["RECEIVED_WRONG_ITEM"] = "RECEIVED_WRONG_ITEM";
    EscalateReasonEnum["SELLER_NO_RESPONSE"] = "SELLER_NO_RESPONSE";
    EscalateReasonEnum["TROUBLE_COMMUNICATION_WITH_BUYER"] = "TROUBLE_COMMUNICATION_WITH_BUYER";
    EscalateReasonEnum["TROUBLE_COMMUNICATION_WITH_SELLER"] = "TROUBLE_COMMUNICATION_WITH_SELLER";
})(EscalateReasonEnum = exports.EscalateReasonEnum || (exports.EscalateReasonEnum = {}));
var DecisionEnum;
(function (DecisionEnum) {
    DecisionEnum["ACCEPT_PARTIAL_REFUND"] = "ACCEPT_PARTIAL_REFUND";
    DecisionEnum["ACCEPT_REPLACEMENT_OFFER"] = "ACCEPT_REPLACEMENT_OFFER";
    DecisionEnum["APPROVE"] = "APPROVE";
    DecisionEnum["APPROVE_WITHOUT_EBAY_LABEL"] = "APPROVE_WITHOUT_EBAY_LABEL";
    DecisionEnum["DECLINE"] = "DECLINE";
    DecisionEnum["DECLINE_PARTIAL_REFUND"] = "DECLINE_PARTIAL_REFUND";
    DecisionEnum["DECLINE_REPLACEMENT_OFFER"] = "DECLINE_REPLACEMENT_OFFER";
    DecisionEnum["OFFER_PARTIAL_REFUND"] = "OFFER_PARTIAL_REFUND";
    DecisionEnum["OFFER_REPLACEMENT"] = "OFFER_REPLACEMENT";
    DecisionEnum["OFFER_RETURN"] = "OFFER_RETURN";
    DecisionEnum["OFFER_RETURN_WITHOUT_LABEL"] = "OFFER_RETURN_WITHOUT_LABEL";
    DecisionEnum["PROVIDE_RMA"] = "PROVIDE_RMA";
    DecisionEnum["UNKNOWN"] = "UNKNOWN";
})(DecisionEnum = exports.DecisionEnum || (exports.DecisionEnum = {}));
var ReturnCountFilterEnum;
(function (ReturnCountFilterEnum) {
    ReturnCountFilterEnum["ALL_OPEN"] = "ALL_OPEN";
    ReturnCountFilterEnum["ALL_OPEN_REPLACEMENT"] = "ALL_OPEN_REPLACEMENT";
    ReturnCountFilterEnum["ALL_OPEN_RETURN"] = "ALL_OPEN_RETURN";
    ReturnCountFilterEnum["CLOSED"] = "CLOSED";
    ReturnCountFilterEnum["EBAY_PLUS"] = "EBAY_PLUS";
    ReturnCountFilterEnum["ITEM_DELIVERED"] = "ITEM_DELIVERED";
    ReturnCountFilterEnum["ITEM_SHIPPED"] = "ITEM_SHIPPED";
    ReturnCountFilterEnum["RETURN_STARTED"] = "RETURN_STARTED";
    ReturnCountFilterEnum["SELLER_ACTION_DUE"] = "SELLER_ACTION_DUE";
    ReturnCountFilterEnum["SELLER_ACTION_OVERDUE"] = "SELLER_ACTION_OVERDUE";
    ReturnCountFilterEnum["SELLER_NO_ACTION"] = "SELLER_NO_ACTION";
    ReturnCountFilterEnum["UNKNOWN"] = "UNKNOWN";
})(ReturnCountFilterEnum = exports.ReturnCountFilterEnum || (exports.ReturnCountFilterEnum = {}));
var ReturnStateEnum;
(function (ReturnStateEnum) {
    ReturnStateEnum["AUTO_REFUND_INITIATED"] = "AUTO_REFUND_INITIATED";
    ReturnStateEnum["CLOSED"] = "CLOSED";
    ReturnStateEnum["INITIAL"] = "INITIAL";
    ReturnStateEnum["ITEM_DELIVERED"] = "ITEM_DELIVERED";
    ReturnStateEnum["ITEM_KEPT"] = "ITEM_KEPT";
    ReturnStateEnum["ITEM_READY_TO_SHIP"] = "ITEM_READY_TO_SHIP";
    ReturnStateEnum["ITEM_SHIPPED"] = "ITEM_SHIPPED";
    ReturnStateEnum["LESS_THAN_A_FULL_REFUND_ISSUED"] = "LESS_THAN_A_FULL_REFUND_ISSUED";
    ReturnStateEnum["PARTIAL_REFUND_AS_PAYOUT_INITIATED"] = "PARTIAL_REFUND_AS_PAYOUT_INITIATED";
    ReturnStateEnum["PARTIAL_REFUND_DECLINED"] = "PARTIAL_REFUND_DECLINED";
    ReturnStateEnum["PARTIAL_REFUND_FAILED"] = "PARTIAL_REFUND_FAILED";
    ReturnStateEnum["PARTIAL_REFUND_INITIATED"] = "PARTIAL_REFUND_INITIATED";
    ReturnStateEnum["PARTIAL_REFUND_NON_PAYPAL_INITIATED"] = "PARTIAL_REFUND_NON_PAYPAL_INITIATED";
    ReturnStateEnum["PARTIAL_REFUND_REQUESTED"] = "PARTIAL_REFUND_REQUESTED";
    ReturnStateEnum["PARTIAL_REFUNDED"] = "PARTIAL_REFUNDED";
    ReturnStateEnum["PAYOUT_INITIATED"] = "PAYOUT_INITIATED";
    ReturnStateEnum["REFUND_AS_PAYOUT_INITIATED"] = "REFUND_AS_PAYOUT_INITIATED";
    ReturnStateEnum["REFUND_FAILED"] = "REFUND_FAILED";
    ReturnStateEnum["REFUND_INITIATED"] = "REFUND_INITIATED";
    ReturnStateEnum["REFUND_SENT_PENDING_CONFIRMATION"] = "REFUND_SENT_PENDING_CONFIRMATION";
    ReturnStateEnum["REFUND_TIMEOUT"] = "REFUND_TIMEOUT";
    ReturnStateEnum["REPLACED"] = "REPLACED";
    ReturnStateEnum["REPLACEMENT_CLOSED"] = "REPLACEMENT_CLOSED";
    ReturnStateEnum["REPLACEMENT_DELIVERED"] = "REPLACEMENT_DELIVERED";
    ReturnStateEnum["REPLACEMENT_LABEL_PENDING"] = "REPLACEMENT_LABEL_PENDING";
    ReturnStateEnum["REPLACEMENT_LABEL_PENDING_TIMEOUT"] = "REPLACEMENT_LABEL_PENDING_TIMEOUT";
    ReturnStateEnum["REPLACEMENT_LABEL_REQUESTED"] = "REPLACEMENT_LABEL_REQUESTED";
    ReturnStateEnum["REPLACEMENT_LABEL_REQUESTED_TIMEOUT"] = "REPLACEMENT_LABEL_REQUESTED_TIMEOUT";
    ReturnStateEnum["REPLACEMENT_OFFER_PENDING"] = "REPLACEMENT_OFFER_PENDING";
    ReturnStateEnum["REPLACEMENT_REQUEST_TIMEOUT"] = "REPLACEMENT_REQUEST_TIMEOUT";
    ReturnStateEnum["REPLACEMENT_REQUESTED"] = "REPLACEMENT_REQUESTED";
    ReturnStateEnum["REPLACEMENT_RMA_PENDING"] = "REPLACEMENT_RMA_PENDING";
    ReturnStateEnum["REPLACEMENT_SHIPPED"] = "REPLACEMENT_SHIPPED";
    ReturnStateEnum["REPLACEMENT_STARTED"] = "REPLACEMENT_STARTED";
    ReturnStateEnum["RETURN_LABEL_PENDING"] = "RETURN_LABEL_PENDING";
    ReturnStateEnum["RETURN_LABEL_PENDING_TIMEOUT"] = "RETURN_LABEL_PENDING_TIMEOUT";
    ReturnStateEnum["RETURN_LABEL_REQUESTED"] = "RETURN_LABEL_REQUESTED";
    ReturnStateEnum["RETURN_LABEL_REQUESTED_TIMEOUT"] = "RETURN_LABEL_REQUESTED_TIMEOUT";
    ReturnStateEnum["RETURN_REJECTED"] = "RETURN_REJECTED";
    ReturnStateEnum["RETURN_REQUEST_TIMEOUT"] = "RETURN_REQUEST_TIMEOUT";
    ReturnStateEnum["RETURN_REQUESTED"] = "RETURN_REQUESTED";
    ReturnStateEnum["RMA_PENDING"] = "RMA_PENDING";
    ReturnStateEnum["UNKNOWN"] = "UNKNOWN";
})(ReturnStateEnum = exports.ReturnStateEnum || (exports.ReturnStateEnum = {}));
var FilePurposeEnum;
(function (FilePurposeEnum) {
    FilePurposeEnum["ITEM_RELATED"] = "ITEM_RELATED";
    FilePurposeEnum["LABEL_RELATED"] = "LABEL_RELATED";
    FilePurposeEnum["REFUND_RELATED"] = "REFUND_RELATED";
    FilePurposeEnum["UNKNOWN"] = "UNKNOWN";
})(FilePurposeEnum = exports.FilePurposeEnum || (exports.FilePurposeEnum = {}));
var RefundFeeTypeEnum;
(function (RefundFeeTypeEnum) {
    RefundFeeTypeEnum["DOMESTIC_SHIPPING"] = "DOMESTIC_SHIPPING";
    RefundFeeTypeEnum["IMPORT_CHARGE"] = "IMPORT_CHARGE";
    RefundFeeTypeEnum["INTERNATIONAL_SHIPPING"] = "INTERNATIONAL_SHIPPING";
    RefundFeeTypeEnum["ITEM_IMPORT_TAX"] = "ITEM_IMPORT_TAX";
    RefundFeeTypeEnum["ITEM_TAX"] = "ITEM_TAX";
    RefundFeeTypeEnum["ORDER_ADJUSTMENT"] = "ORDER_ADJUSTMENT";
    RefundFeeTypeEnum["ORIGINAL_SHIPPING"] = "ORIGINAL_SHIPPING";
    RefundFeeTypeEnum["OTHER"] = "OTHER";
    RefundFeeTypeEnum["PURCHASE_PRICE"] = "PURCHASE_PRICE";
    RefundFeeTypeEnum["REFUND_FROM_PAYPAL"] = "REFUND_FROM_PAYPAL";
    RefundFeeTypeEnum["RETURN_SHIPPING"] = "RETURN_SHIPPING";
    RefundFeeTypeEnum["SHIPPING_IMPORT_TAX"] = "SHIPPING_IMPORT_TAX";
    RefundFeeTypeEnum["SHIPPING_TAX"] = "SHIPPING_TAX";
})(RefundFeeTypeEnum = exports.RefundFeeTypeEnum || (exports.RefundFeeTypeEnum = {}));
var ActivityOptionEnum;
(function (ActivityOptionEnum) {
    ActivityOptionEnum["AUTO_APPROVE_REMORSE"] = "AUTO_APPROVE_REMORSE";
    ActivityOptionEnum["BUYER_ACCEPT_REPLACEMENT_OFFER"] = "BUYER_ACCEPT_REPLACEMENT_OFFER";
    ActivityOptionEnum["BUYER_ACCEPTS_NON_PAYPAL_PARTIAL_REFUND"] = "BUYER_ACCEPTS_NON_PAYPAL_PARTIAL_REFUND";
    ActivityOptionEnum["BUYER_ACCEPTS_PARTIAL_REFUND"] = "BUYER_ACCEPTS_PARTIAL_REFUND";
    ActivityOptionEnum["BUYER_CLOSE_RETURN"] = "BUYER_CLOSE_RETURN";
    ActivityOptionEnum["BUYER_CREATE_RETURN"] = "BUYER_CREATE_RETURN";
    ActivityOptionEnum["BUYER_DECLINE_PARTIAL_REFUND"] = "BUYER_DECLINE_PARTIAL_REFUND";
    ActivityOptionEnum["BUYER_DECLINE_REPLACEMENT_OFFER"] = "BUYER_DECLINE_REPLACEMENT_OFFER";
    ActivityOptionEnum["BUYER_ESCALATE"] = "BUYER_ESCALATE";
    ActivityOptionEnum["BUYER_MARK_AS_RECEIVED"] = "BUYER_MARK_AS_RECEIVED";
    ActivityOptionEnum["BUYER_MARK_REFUND_RECEIVED"] = "BUYER_MARK_REFUND_RECEIVED";
    ActivityOptionEnum["BUYER_MARK_RETURN_SHIPPED"] = "BUYER_MARK_RETURN_SHIPPED";
    ActivityOptionEnum["BUYER_PRINT_SHIPPING_LABEL"] = "BUYER_PRINT_SHIPPING_LABEL";
    ActivityOptionEnum["BUYER_PROVIDE_LABEL"] = "BUYER_PROVIDE_LABEL";
    ActivityOptionEnum["BUYER_PROVIDE_TRACKING_INFO"] = "BUYER_PROVIDE_TRACKING_INFO";
    ActivityOptionEnum["BUYER_SEND_MESSAGE"] = "BUYER_SEND_MESSAGE";
    ActivityOptionEnum["BUYER_UPDATE_TRACKING"] = "BUYER_UPDATE_TRACKING";
    ActivityOptionEnum["BUYER_VOID_LABEL"] = "BUYER_VOID_LABEL";
    ActivityOptionEnum["CHARGEBACK_OPEN"] = "CHARGEBACK_OPEN";
    ActivityOptionEnum["DELETE_FILE"] = "DELETE_FILE";
    ActivityOptionEnum["EMAIL_SHIPPING_LABEL"] = "EMAIL_SHIPPING_LABEL";
    ActivityOptionEnum["EXTERNAL_CLAIM_OPENED"] = "EXTERNAL_CLAIM_OPENED";
    ActivityOptionEnum["GENERAL_TIME_OUT"] = "GENERAL_TIME_OUT";
    ActivityOptionEnum["NOTIFIED_DELIVERED"] = "NOTIFIED_DELIVERED";
    ActivityOptionEnum["NOTIFIED_SHIPPED"] = "NOTIFIED_SHIPPED";
    ActivityOptionEnum["NOTIFY_REPLACEMENT_DELIVERED"] = "NOTIFY_REPLACEMENT_DELIVERED";
    ActivityOptionEnum["NOTIFY_REPLACEMENT_SHIPPED"] = "NOTIFY_REPLACEMENT_SHIPPED";
    ActivityOptionEnum["NOTIFY_UPDATE_REFUND_STATUS"] = "NOTIFY_UPDATE_REFUND_STATUS";
    ActivityOptionEnum["OTHER"] = "OTHER";
    ActivityOptionEnum["REMINDER_BUYER_TO_RESPOND_RE_OFFER"] = "REMINDER_BUYER_TO_RESPOND_RE_OFFER";
    ActivityOptionEnum["REMINDER_BUYER_TO_SHIP"] = "REMINDER_BUYER_TO_SHIP";
    ActivityOptionEnum["REMINDER_FOR_REFUND"] = "REMINDER_FOR_REFUND";
    ActivityOptionEnum["REMINDER_FOR_REFUND_NO_SHIPPING"] = "REMINDER_FOR_REFUND_NO_SHIPPING";
    ActivityOptionEnum["REMINDER_FOR_RMA"] = "REMINDER_FOR_RMA";
    ActivityOptionEnum["REMINDER_FOR_SHIPPING"] = "REMINDER_FOR_SHIPPING";
    ActivityOptionEnum["REMINDER_SELLER_TO_RESPOND"] = "REMINDER_SELLER_TO_RESPOND";
    ActivityOptionEnum["REMINDER_SELLER_TO_SHIP"] = "REMINDER_SELLER_TO_SHIP";
    ActivityOptionEnum["SELLER_APPROVE_REQUEST"] = "SELLER_APPROVE_REQUEST";
    ActivityOptionEnum["SELLER_DECLINE_REQUEST"] = "SELLER_DECLINE_REQUEST";
    ActivityOptionEnum["SELLER_ESCALATE"] = "SELLER_ESCALATE";
    ActivityOptionEnum["SELLER_ISSUE_REFUND"] = "SELLER_ISSUE_REFUND";
    ActivityOptionEnum["SELLER_ISSUE_STORE_CREDIT_REFUND"] = "SELLER_ISSUE_STORE_CREDIT_REFUND";
    ActivityOptionEnum["SELLER_MARK_AS_RECEIVED"] = "SELLER_MARK_AS_RECEIVED";
    ActivityOptionEnum["SELLER_MARK_REFUND_SENT"] = "SELLER_MARK_REFUND_SENT";
    ActivityOptionEnum["SELLER_MARK_REPLACEMENT_SHIPPED"] = "SELLER_MARK_REPLACEMENT_SHIPPED";
    ActivityOptionEnum["SELLER_OFFER_PARTIAL_REFUND"] = "SELLER_OFFER_PARTIAL_REFUND";
    ActivityOptionEnum["SELLER_OFFER_REPLACEMENT"] = "SELLER_OFFER_REPLACEMENT";
    ActivityOptionEnum["SELLER_OFFER_RETURNS"] = "SELLER_OFFER_RETURNS";
    ActivityOptionEnum["SELLER_PRINT_SHIPPING_LABEL"] = "SELLER_PRINT_SHIPPING_LABEL";
    ActivityOptionEnum["SELLER_PROVIDE_LABEL"] = "SELLER_PROVIDE_LABEL";
    ActivityOptionEnum["SELLER_PROVIDE_RMA"] = "SELLER_PROVIDE_RMA";
    ActivityOptionEnum["SELLER_PROVIDE_TRACKING_INFO"] = "SELLER_PROVIDE_TRACKING_INFO";
    ActivityOptionEnum["SELLER_RETRY_REFUND"] = "SELLER_RETRY_REFUND";
    ActivityOptionEnum["SELLER_SEND_MESSAGE"] = "SELLER_SEND_MESSAGE";
    ActivityOptionEnum["SELLER_UPDATE_TRACKING"] = "SELLER_UPDATE_TRACKING";
    ActivityOptionEnum["SELLER_VOID_LABEL"] = "SELLER_VOID_LABEL";
    ActivityOptionEnum["SUBMIT_FILE"] = "SUBMIT_FILE";
    ActivityOptionEnum["SYSTEM_BUYER_PARTIAL_REFUND_AS_PAYOUT"] = "SYSTEM_BUYER_PARTIAL_REFUND_AS_PAYOUT";
    ActivityOptionEnum["SYSTEM_BUYER_REFUND_AS_PAYOUT"] = "SYSTEM_BUYER_REFUND_AS_PAYOUT";
    ActivityOptionEnum["SYSTEM_CLOSE_RETURN"] = "SYSTEM_CLOSE_RETURN";
    ActivityOptionEnum["SYSTEM_CREATE_RETURN"] = "SYSTEM_CREATE_RETURN";
    ActivityOptionEnum["SYSTEM_IMMEDIATE_REFUND"] = "SYSTEM_IMMEDIATE_REFUND";
    ActivityOptionEnum["TIME_OUT_AFTER_DECLINE"] = "TIME_OUT_AFTER_DECLINE";
    ActivityOptionEnum["TIME_OUT_AFTER_REFUNDED"] = "TIME_OUT_AFTER_REFUNDED";
    ActivityOptionEnum["TIME_OUT_AFTER_REFUNDED_AS_PAYOUT"] = "TIME_OUT_AFTER_REFUNDED_AS_PAYOUT";
    ActivityOptionEnum["TIME_OUT_AFTER_REPLACED"] = "TIME_OUT_AFTER_REPLACED";
    ActivityOptionEnum["TIME_OUT_FOR_AUTHORIZE"] = "TIME_OUT_FOR_AUTHORIZE";
    ActivityOptionEnum["TIME_OUT_FOR_AUTO_REFUND"] = "TIME_OUT_FOR_AUTO_REFUND";
    ActivityOptionEnum["TIME_OUT_FOR_BUYER_RECOUP"] = "TIME_OUT_FOR_BUYER_RECOUP";
    ActivityOptionEnum["TIME_OUT_FOR_DELIVERY"] = "TIME_OUT_FOR_DELIVERY";
    ActivityOptionEnum["TIME_OUT_FOR_ESCALATION"] = "TIME_OUT_FOR_ESCALATION";
    ActivityOptionEnum["TIME_OUT_FOR_ESCALATION_AFTER_SMIR"] = "TIME_OUT_FOR_ESCALATION_AFTER_SMIR";
    ActivityOptionEnum["TIME_OUT_FOR_ITEM_REPLACED"] = "TIME_OUT_FOR_ITEM_REPLACED";
    ActivityOptionEnum["TIME_OUT_FOR_MARK_REFUND_RECEIVED"] = "TIME_OUT_FOR_MARK_REFUND_RECEIVED";
    ActivityOptionEnum["TIME_OUT_FOR_MARK_REFUND_SENT"] = "TIME_OUT_FOR_MARK_REFUND_SENT";
    ActivityOptionEnum["TIME_OUT_FOR_MASS_PAYOUT"] = "TIME_OUT_FOR_MASS_PAYOUT";
    ActivityOptionEnum["TIME_OUT_FOR_PAYOUT"] = "TIME_OUT_FOR_PAYOUT";
    ActivityOptionEnum["TIME_OUT_FOR_PROVIDE_LABEL"] = "TIME_OUT_FOR_PROVIDE_LABEL";
    ActivityOptionEnum["TIME_OUT_FOR_REFUND"] = "TIME_OUT_FOR_REFUND";
    ActivityOptionEnum["TIME_OUT_FOR_REPLACEMENT_DELIVERED_ITEM_NOT_RETURNED"] = "TIME_OUT_FOR_REPLACEMENT_DELIVERED_ITEM_NOT_RETURNED";
    ActivityOptionEnum["TIME_OUT_FOR_REPLACEMENT_SHIPPED"] = "TIME_OUT_FOR_REPLACEMENT_SHIPPED";
    ActivityOptionEnum["TIME_OUT_FOR_RETURN_SHIPPING"] = "TIME_OUT_FOR_RETURN_SHIPPING";
    ActivityOptionEnum["TIME_OUT_FOR_RMA"] = "TIME_OUT_FOR_RMA";
    ActivityOptionEnum["TIME_OUT_FOR_SELLER_INVOICE"] = "TIME_OUT_FOR_SELLER_INVOICE";
    ActivityOptionEnum["TIME_OUT_FOR_SELLER_PAYOUT"] = "TIME_OUT_FOR_SELLER_PAYOUT";
    ActivityOptionEnum["TIME_OUT_FOR_SHIPMENT_TRACKING"] = "TIME_OUT_FOR_SHIPMENT_TRACKING";
    ActivityOptionEnum["TIME_OUT_FOR_SHIPPING"] = "TIME_OUT_FOR_SHIPPING";
    ActivityOptionEnum["TIME_OUT_FOR_SHIPPING_SYSTEM_CLOSE"] = "TIME_OUT_FOR_SHIPPING_SYSTEM_CLOSE";
})(ActivityOptionEnum = exports.ActivityOptionEnum || (exports.ActivityOptionEnum = {}));
//# sourceMappingURL=enums.js.map